### ISSUE TITLE
I wanted to withdraw my $PAC and it showed ERROR

### ISSUE THREAD

**Issue by romanzmykulova** [atomiclabs/hyperdex#438] opened 2018-07-20 15:12 UTC
I wanted to withdraw all my ballance of 999.9999 PAC

Unhandled Promise Rejection
Error: Couldn't create withdrawal transaction:
{ txid: '0000000000000000000000000000000000000000000000000000000000000000',
  txfee: 10000,
  complete: false }
    at errorWithObject (app://-/bundle.js:88119:46)
    at app://-/bundle.js:88386:11
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:88104:191)
    at app://-/bundle.js:88104:361
    at <anonymous>

---

HyperDEX 0.1.0-alpha.10
Electron 2.0.5
win32 10.0.17134
Locale: cs

**Comment by sindresorhus** [comment] 2018-07-20 15:24
We currently don't calculate the txfee, so you can't withdraw the whole balance at once. Try reducing it to 95% of the whole balance and it should in theory work. We plan on fixing this soon, but it's not that easy because of dynamic txfees.

**Comment by sindresorhus** [comment] 2018-07-20 15:24
Duplicate of #302

**Closed by sindresorhus** 2018-07-20 15:24 UTC
