### ISSUE TITLE
Using "Max" for Withdraw doesn't account for tx fee

### ISSUE THREAD

**Issue by theblackmallard** [atomiclabs/hyperdex#487] opened 2018-08-26 16:28 UTC
Just a small bug/feature. Noticed I get the following error:

Unhandled Promise Rejection
Error: Couldn't create withdrawal transaction:
{ txid: '0000000000000000000000000000000000000000000000000000000000000000',
  txfee: 1000,
  complete: false }
    at errorWithObject (app://-/bundle.js:88740:46)
    at app://-/bundle.js:89018:11
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:88725:191)
    at app://-/bundle.js:88725:361
    at <anonymous>

When I use the Max button for withdrawing a coin. The max button inputs the entire coin balance but doesn't account for the tx fee necessary. No issues with manually accounting for the tx fees/withdraw but this might be a good feature to have. Max meaning the max amount you can withdraw after the tx fee.

**Comment by kevva** [comment] 2018-08-27 18:57
This sounds like a duplicate of https://github.com/atomiclabs/hyperdex/issues/302.

**Closed by kevva** 2018-08-27 18:57 UTC
