### ISSUE TITLE
ETH withdrawal do not working 

### ISSUE THREAD

**Issue by alevlaslo** [atomiclabs/hyperdex#530] opened 2018-09-21 18:54 UTC
---

HyperDEX 0.1.3
Electron 3.0.0
win32 10.0.17134
Locale: ru

**Comment by alevlaslo** [comment] 2018-09-21 18:56
[url=https://radikal.ru][img]https://c.radikal.ru/c21/1809/d5/d2b54b455d37.png[/img][/url]

**Comment by alevlaslo** [comment] 2018-09-24 13:08
thanks


>Понедельник, 24 сентября 2018, 14:26 +03:00 от Sindre Sorhus <notifications@github.com>:
>
>Did you get the error while trying to withdraw the whole balance? We're currently not calculating transmission fee, so withdrawing the whole balance won't work. See  #302 .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Александр

**Comment by sindresorhus** [comment] 2018-09-25 08:47
Duplicate of #302

**Closed by sindresorhus** 2018-09-25 08:47 UTC
