### ISSUE TITLE
Error when trying to go to the Market Menu

### ISSUE THREAD

**Issue by Erlix322** [atomiclabs/hyperdex#459] opened 2018-08-02 04:30 UTC
Unhandled Promise Rejection
TypeError: Cannot read property 'find' of undefined
    at messages.forEach.message (app://-/bundle.js:98917:39)
    at Array.forEach (<anonymous>)
    at _formatSwap (app://-/bundle.js:98873:12)
    at Array.map (<anonymous>)
    at app://-/bundle.js:99021:20
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:98707:191)
    at app://-/bundle.js:98707:361
    at <anonymous>

![hyperhyper](https://user-images.githubusercontent.com/16254580/43562602-c844c7ce-961d-11e8-9463-ef8069f72e8e.PNG)

**Comment by sindresorhus** [comment] 2018-08-02 07:08
Duplicate of #456

**Closed by sindresorhus** 2018-08-02 07:08 UTC
