### ISSUE TITLE
Swaps stop after `Swapping 2/5`

### ISSUE THREAD

**Issue by ptyx11** [atomiclabs/hyperdex#493] opened 2018-08-30 00:09 UTC
I've been having issues with swaps getting stuck 2/5. i've made sure there is a miner for the assetchain so confirmations are happening constantly. this is happening with the zilla/kmd pair

---

HyperDEX 0.1.0-alpha.12
Electron 2.0.6
darwin 17.7.0
Locale: en-US

**Comment by ptyx11** [comment] 2018-08-30 00:10
Also the app freezes and it doesn't show that the swap has failed even after 20 minutes.

**Comment by sindresorhus** [comment] 2018-08-31 07:09
By "freezes" do you mean the UI freezes and you can't click anything or do you mean that just Marketmaker stops sending updates?

**Comment by lukechilds** [comment] 2018-09-12 23:04
The atomic swap protocol can take up to 4 hours to complete if there are communications issues between Alice <-> Bob. I don't think there is anything wrong here other than the swaps taking a long time to complete.

I can complete a ZILLA swap, although it did take a while: https://github.com/atomiclabs/hyperdex/issues/498#issuecomment-418426656

Is this issue a duplicate of #498 or is this a separate issue?

**Comment by lukechilds** [comment] 2018-09-18 21:07
Closing as dupe of https://github.com/atomiclabs/hyperdex/issues/498

**Closed by lukechilds** 2018-09-18 21:07 UTC
